# Dear curious person:
#
# These are not the real keys to the kingdom. They are, however, used during
# development; Or more appropriately used as a frame of reference for our
# development.
#
# They are included so we can share what the keys should be.
curate_batch_api_key: '12345'
curate_batch_group_pid: "group_pid"
curate_nd_url_for_etds: "https://curate.nd.edu/catalog?f_inclusive%5Bhuman_readable_type_sim%5D%5B%5D=Doctoral+Dissertation&f_inclusive%5Bhuman_readable_type_sim%5D%5B%5D=Master%27s+Thesis"
curate_nd_url_show_prefix_url: "https://curate.nd.edu/show/"
default_email_from: 'sipity-development@nd.edu'
default_email_return_path: 'no-reply@nd.edu'
doi_shoulder: "doi:10.xxxx"
dragonfly_s3_access_key_id: 's3_key'
dragonfly_s3_bucket_name: 'bucket_name'
dragonfly_s3_root_path: 's3_root_dir'
dragonfly_s3_path: "path"
dragonfly_s3_secret_access_key: 'secret'
dragonfly_s3_url_host: 'bucketname.aws.com'
dragonfly_secret: "12345"
hesburgh_api_auth_token: '12345'
hesburgh_api_host: https://api.library.nd.edu/
noid_pool: 'pool_name'
noid_port: '3000'
noid_server: 'noidserver.com'
protocol: 'http'
sentry_dsn: 'fakey-mcfake-face'
sipity_access_key_for_batch_ingester: '1234'
sipity_access_key_for_etd_integrators: '4567'
sipity_batch_ingester_access_key: '1234' # deprecated
smtp_host: "smtp.gmail.com"
smtp_port: '587'
smtp_domain: "gmail.com"
smtp_authentication_type: "plain"
smtp_user_name: "noreply@nd.edu"
smtp_enable_starttls_auto: "true"
smtp_delivery_method: "smtp"

development:
  domain_name: "localhost:3000"
  url_host: "https://localhost:3000"
  secret_key_base: 'bd6953190e19dabc215af75a5c856f584dca49a3ab729696946a80ec50f46094d4643d908b88b07011f898f5c6748f2ffa832c96bae409e5462f2cf3055f1ee7'
  okta_auth_server_id: fakey
  okta_auth_url: fakey
  okta_client_id: fakey
  okta_client_secret: fakey
  okta_redirect_uri: fakey
  okta_site: fakey
  okta_token_url: fakey
  curate_batch_user_pid: "batch_user_pid"
  curate_grad_school_editing_group_pid: "batch_group_pid"
  curate_batch_data_mount_path: "local/data"
  curate_batch_queue_mount_path: "local/queue"
  curate_batch_api_base_path: "http://localhost:15000/jobs"

  # sentry_dsn: 'put something here if you want it for testing'


test:
  domain_name: "localhost:3000"
  okta_auth_server_id: fakey
  okta_auth_url: fakey
  okta_client_id: fakey
  okta_client_secret: fakey
  okta_redirect_uri: fakey
  okta_site: fakey
  okta_token_url: fakey
  url_host: "https://localhost:3000"
  secret_key_base: 'bd6953190e19dabc215af75a5c856f584dca49a3ab729696946a80ec50f46094d4643d908b88b07011f898f5c6748f2ffa832c96bae409e5462f2cf3055f1ee7'
  curate_batch_user_pid: "batch_user_pid"
  curate_grad_school_editing_group_pid: "batch_group_pid"
  curate_batch_data_mount_path: "tmp/data"
  curate_batch_queue_mount_path: "tmp/queue"
  curate_batch_api_base_path: "tmp/jobs"
