##########################################
# Shared settings
##########################################

mysql_settings: &mysql_settings
  adapter: mysql2
  pool: 5
  encoding: utf8
  reconnect: false
  timeout: 5000

##########################################
# Environments
##########################################

development:
  <<: *mysql_settings
#   database: <%= Rails.application.secrets.database["database"] %>
#   username: <%= Rails.application.secrets.database["username"] %>
  database: sipity_development
  username: root

# development:
#   <<: *mysql_settings
#   host: <%= Rails.application.secrets.database["host"] %>
#   database: <%= Rails.application.secrets.database["database"] %>
#   username: <%= Rails.application.secrets.database["username"] %>
#   password: <%= Rails.application.secrets.database["password"] %>

test: &test
  <<: *mysql_settings
  database: <%= Rails.application.secrets.database["database"] %>
  username: <%= Rails.application.secrets.database["username"] %>

prep:
  <<: *mysql_settings
  host: <%= Rails.application.secrets.database["host"] %>
  database: <%= Rails.application.secrets.database["database"] %>
  username: <%= Rails.application.secrets.database["username"] %>
  password: <%= Rails.application.secrets.database["password"] %>


pre_production:
  <<: *mysql_settings
  host: <%= Rails.application.secrets.database["host"] %>
  database: <%= Rails.application.secrets.database["database"] %>
  username: <%= Rails.application.secrets.database["username"] %>
  password: <%= Rails.application.secrets.database["password"] %>

production:
  <<: *mysql_settings
  host: <%= Rails.application.secrets.database["host"] %>
  database: <%= Rails.application.secrets.database["database"] %>
  username: <%= Rails.application.secrets.database["username"] %>
  password: <%= Rails.application.secrets.database["password"] %>
