# Dear curious person:
#
# These are not the real keys to the kingdom. They are, however, used during
# development; Or more appropriately used as a frame of reference for our
# development.
#
# They are included so we can share what the keys should be.
development: &development
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>
  database:
    username: "root"
    database: "sipity_development"

test:
  <<: *development
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production: &production
  admin_name: <%= Figaro.env.admin_name %>
  admin_email: <%= Figaro.env.admin_email %>
  admin_password: <%= Figaro.env.admin_password %>
  domain_name: <%= Figaro.env.domain_name %>
  secret_key_base: <%= Figaro.env.secret_key_base %>

prep:
  <<: *production

prep26:
  <<: *production
