name: sipity-ci
on:
  push:
jobs:
  test-sipity:
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6

    - name: Update System Gems
      run: gem update --system 

    - name: Install bundler
      run: gem install bundler -v 2.2.10

    - name: Install bundled dependencies
      run: bundle install --without development debug doc

    - name: start mysql DB
      run: sudo service mysql start

    - name: create sipity_test DB
      run:  mysql -e "CREATE DATABASE sipity_test;" -uroot -proot

    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        RAILS_ENV: test
        CC_TEST_REPORTER_ID: ${{ secrets.CODE_CLIMATE_REPORTER_ID }}
      with:
        coverageCommand: bundle exec rake spec:ci
        debug: true
